config/routes.rb
Warmup::Application.routes.draw do

  match "users/add" => "clients#add", :as => "add", :via => "post", :defaults => { :format => 'json' }
  match "users/login" => "clients#login", :as => "login", :via => "post", :defaults => { :format => 'json' }
  match "TESTAPI/resetFixture" => "clients#resetFixture", :as => "reset", :via => "post", :defaults => { :format => 'json' }
  match "TESTAPI/unitTests" => "clients#unitTests", :as => "test", :via => "post", :defaults => { :format => 'json' }
  match "users" => "clients#client", :via => 'get'

  root :to => 'clients#client'

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :username, :password

  #different situations correspond to different errcodes
  SUCCESS = 1
  ERR_BAD_CREDENTIALS = -1
  ERR_USER_EXISTS = -2
  ERR_BAD_USERNAME = -3
  ERR_BAD_PASSWORD = -4

  #login function with two parameters (username, password) passed in
  def login(user, password)
  	@client = Client.where(:username => user).first
    if @client.nil? || @client.password != password
      return ERR_BAD_CREDENTIALS
    else
      @client.count +=1
      @client.save
      return @client.count
    end
  end

  #add user functiion with two parameters (username, password) passed in 
  def add(user, password)
  	@client = Client.where(:username => user).first
    if user.length == 0 || user.length > 128
      return ERR_BAD_USERNAME
    elsif password.length > 128
      return ERR_BAD_PASSWORD
    elsif !@client.nil?
      return ERR_USER_EXISTS
    else
      @client = Client.new(:username => user, :password => password)
      @client.count = 1
      @client.save
      return SUCCESS
    end
  end

  #delete all the data in database
  def TESTAPI_resetFixture()
	  Client.delete_all
	  return SUCCESS
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  #client function: GET clients
  def client
      respond_to do |format|
          format.html { render :action => "client" }
      end
  end

  #login function: POST /users/login
  def login
    #handle unexpected error with status code 500
    begin
      if request.env['CONTENT_TYPE'].include?('application/json') 
        @client = Client.new
        errCode = @client.login(params[:user], params[:password])
        if errCode > 0
          dic = {:errCode => 1, :count => errCode}
          respond_to do |format|
            format.json { render json: dic, :status => 200 }
          end
        else
          dic = {:errCode => errCode}
          respond_to do |format|
            format.json { render json: dic, :status => 200 }
          end
        end
      else
        render :json => { :errors => "Wrong Content-Type on Request'" }, :status => 500
      end
    rescue
      render :json => { :errors => "Unknown Errors" }, :status => 500
    end
  end

  #add function: POST /users/add
  def add
    #handle unexpected error with status code 500
    begin
      if request.env['CONTENT_TYPE'].include?('application/json') 
        @client = Client.new
        @username = params[:user]
        @password = params[:password]
        errCode = @client.add(params[:user], params[:password])
        if errCode > 0
          dic = {:errCode => 1, :count => errCode}
          respond_to do |format|
            format.json { render json: dic, :status => 200 }
          end
        else
          dic = {:errCode => errCode}
          respond_to do |format|
            format.json { render json: dic, :status => 200 }
          end
        end
      else
        render :json => { :errors => "Wrong Content-Type on Request'" }, :status => 500
      end
    rescue
      render :json => { :errors => "Unknown Errors" }, :status => 500
    end
  end

  #reset database: POST /TESTAPI/resetFixture 
  def resetFixture
    #handle unexpected error with status code 500
    begin
      @client = Client.new
      errCode = @client.TESTAPI_resetFixture()
      dic = {:errCode => 1}
      respond_to do |format|
        format.json { render json: dic, :status => 200 }
      end
    rescue
      render :json => { :errors => "Unknown Errors" }, :status => 500
    end
  end

  #calling unit tests in test/unit: POST /TESTAPI/unitTests
  def unitTests
    #handle unexpected error with status code 500
    begin
      system("rake test:units > output.txt")
      aFile = File.new("output.txt", "r")
      data = aFile.readlines
      aFile.close()
      totalTests = Integer(data[-1].split(",")[0].split(" ")[0])
      nrFailed = Integer(data[-1].split(",")[-2].split(" ")[0]) + Integer(data[-1].split(",")[-3].split(" ")[0])
      if nrFailed == 0
        dic = {:totalTests => totalTests, :nrFailed => 0, :output => "unitTests all passes"}
      else
        aFile = File.new("output.txt", "r")
        output = aFile.read.split("\n").join
        aFile.close()
        dic = {:totalTests => totalTests, :nrFailed => nrFailed, :output => output}
      end
      respond_to do |format|
        format.json { render json: dic, :status => 200 }
      end
    rescue
      render :json => { :errors => "Unknown Errors" }, :status => 500
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/client.html.erb
<center>
<div id="login-page" class="page">
  <div id="login-message" class="message">
  </div>

  <table>
      <td>Username</td>
      <td><input id="login-username" type="text" name="user" class="text"> </td>

      <td>Password</td>
      <td><input id="login-password" type="password" name="password" class="text"> </td>
  
  </table>
    
  <table>

    <td><input id="login-button" type="submit" value="Login" class="button"> </td>
    <td><input id="add-user-button" type="submit" value="Add User" class="button"> </td>
  
  </table>

</div>

<div id="welcome-page" class="page">
  <div id="welcome-message" class="message">
  </div>
    <input id="logout-button" type="submit" value="Logout" class="button"/>
</div>
</center>

<script type="text/javascript">
  $('#login-page').hide();
  $('#welcome-page').hide();
  $('#login-username').val("");
  $('#login-password').val("");
  $('#login-message').html("Please enter your credentials below.");
  $('#welcome-message').html("You should never see this text");

/* call this function when the login page loaded */
  $(document).ready(function() {
    showLoginPage("Please enter your credentials below.");
  });

/* Just two front-end jquery methods */
function showLoginPage(message) {
    $('#login-page').show();
    $('#welcome-page').hide();
    $('#login-username').val("");
    $('#login-password').val("");
    $('#login-message').html(message);
}

function showWelcomePage(user, count) {
    $('#login-page').hide();
    $('#welcome-page').show();
    $('#welcome-message').html("Welcome " + user + "! You have logged in " + count + " times.");
}

function handleResponse(data, user) {
  if( data.errCode > 0 ) {
    showWelcomePage(user, data.count);
  } else if (data.errCode > -5 || data.errCode < 0) {
    showLoginPage( messageErrcode(data.errCode) );
  } else {
    alert( "Illegal error code encounted for this state");
  }
}

/* helper function for different button response */
function buttonHelper(func) {
  username = $('#login-username').val();
  password = $('#login-password').val();
  jsonRequest(func, { user: username, password: password }, function(data) {return handleResponse(data, username); });
}


/* call when click the Login, Add User and Logout button */
$('#add-user-button').click(function() {
    buttonHelper("/users/add");
    return false;
});

$('#login-button').click(function() {
    buttonHelper("/users/login");
    return false;
});

$('#logout-button').click(function() {
    showLoginPage("Please enter your credentials below.");
    return false;
});
</script>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th>Count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.username %></td>
    <td><%= client.password %></td>
    <td><%= client.count %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
    <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @client.username %>
</p>

<p>
  <b>Password:</b>
  <%= @client.password %>
</p>

<p>
  <b>Count:</b>
  <%= @client.count %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Warmup</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>